# Generated by Django 4.1.1 on 2022-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contrato_Específico_Columna_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Específicos/Documentos/Columna 1",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Específicos/Íconos/Columna 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato Específico Columna 1",
                "verbose_name_plural": "Contrato Específico Columna 1",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contrato_Específico_Columna_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Específicos/Documentos/Columna 2",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Específicos/Íconos/Columna 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato Específico Columna 2",
                "verbose_name_plural": "Contrato Específico Columna 2",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contrato_Específico_Columna_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Específicos/Documentos/Columna 3",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Específicos/Íconos/Columna 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato Específico Columna 3",
                "verbose_name_plural": "Contrato Específico Columna 3",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contrato_General_Columna_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Generales/Documentos/Columna 1",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Generales/Íconos/Columna 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato General Columna 1",
                "verbose_name_plural": "Contrato General Columna 1",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Contrato_General_Columna_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Generales/Documentos/Columna 2",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Generales/Íconos/Columna 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato General Columna 2",
                "verbose_name_plural": "Contrato General Columna 2",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Contrato_General_Columna_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Generales/Documentos/Columna 3",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Contratos Generales/Íconos/Columna 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato General Columna 3",
                "verbose_name_plural": "Contrato General Columna 3",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Documentos_de_Rápido_Acceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Documentos de Rápido Acceso/Documentos/Columna 1",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Documentos de Rápido Acceso/Íconos/Columna 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Rápido Acceso",
                "verbose_name_plural": "Documento Rápido Acceso",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Encabezado_Documentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("texto_1", models.TextField()),
                ("texto_2", models.TextField()),
            ],
            options={
                "verbose_name": "Encabezado Documento",
                "verbose_name_plural": "Encabezado Documento",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Listado_Productos_y_Servicios_Columna_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Listado Productos y Servicios/Documentos/Columna 1",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Listado Productos y Servicios/Íconos/Columna 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listado Productos y Servicios Columna 1",
                "verbose_name_plural": "Listado Productos y Servicios Columna 1",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Listado_Productos_y_Servicios_Columna_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Listado Productos y Servicios/Documentos/Columna 2",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Listado Productos y Servicios/Íconos/Columna 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listado Productos y Servicios Columna 2",
                "verbose_name_plural": "Listado Productos y Servicios Columna 2",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Listado_Productos_y_Servicios_Columna_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Listado Productos y Servicios/Documentos/Columna 3",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Listado Productos y Servicios/Íconos/Columna 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listado Productos y Servicios Columna 3",
                "verbose_name_plural": "Listado Productos y Servicios Columna 3",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Otros_Documentos_Columna_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Otros Documentos/Documentos/Columna 1",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Otros Documentos/Íconos/Columna 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otro Documento Columna 1",
                "verbose_name_plural": "Otro Documento Columna 1",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Otros_Documentos_Columna_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Otros Documentos/Documentos/Columna 2",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Otros Documentos/Íconos/Columna 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otro Documento Columna 2",
                "verbose_name_plural": "Otro Documento Columna 2",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Otros_Documentos_Columna_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Otros Documentos/Documentos/Columna 3",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Otros Documentos/Íconos/Columna 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otro Documento Columna 3",
                "verbose_name_plural": "Otro Documento Columna 3",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Registro_y_Certificaciones_de_Software_Columna_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Registro y Certificaciones de Software/Documentos/Columna 1",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Registro y Certificaciones de Software/Íconos/Columna 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro / Certificación de Software Columna 1",
                "verbose_name_plural": "Registro / Certificación de Software Columna 1",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Registro_y_Certificaciones_de_Software_Columna_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Registro y Certificaciones de Software/Documentos/Columna 2",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Registro y Certificaciones de Software/Íconos/Columna 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro / Certificación de Software Columna 2",
                "verbose_name_plural": "Registro / Certificación de Software Columna 2",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Registro_y_Certificaciones_de_Software_Columna_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Registro y Certificaciones de Software/Documentos/Columna 3",
                    ),
                ),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Documentos/Registro y Certificaciones de Software/Íconos/Columna 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro / Certificación de Software Columna 3",
                "verbose_name_plural": "Registro / Certificación de Software Columna 3",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Texto_Documentos_Rapidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("texto", models.TextField()),
            ],
            options={
                "verbose_name": "Texto Documentos Rápidos",
                "verbose_name_plural": "Texto Documentos Rápidos",
                "ordering": ["id"],
            },
        ),
    ]
