# Generated by Django 4.1.1 on 2022-11-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Documentos",
            "0003_registro_y_certificaciones_de_software_cenda_columna_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contrato_específico_columna_1",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Ctto. Específico Columna 1",
                "verbose_name_plural": "Ctto. Específico Columna 1",
            },
        ),
        migrations.AlterModelOptions(
            name="contrato_específico_columna_2",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Ctto. Específico Columna 2",
                "verbose_name_plural": "Ctto. Específico Columna 2",
            },
        ),
        migrations.AlterModelOptions(
            name="contrato_específico_columna_3",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Ctto.Específico Columna 3",
                "verbose_name_plural": "Ctto. Específico Columna 3",
            },
        ),
        migrations.AlterModelOptions(
            name="contrato_general_columna_1",
            options={
                "ordering": ["id"],
                "verbose_name": "Ctto. General Columna 1",
                "verbose_name_plural": "Ctto. General Columna 1",
            },
        ),
        migrations.AlterModelOptions(
            name="contrato_general_columna_2",
            options={
                "ordering": ["id"],
                "verbose_name": "Ctto. General Columna 2",
                "verbose_name_plural": "Ctto. General Columna 2",
            },
        ),
        migrations.AlterModelOptions(
            name="contrato_general_columna_3",
            options={
                "ordering": ["id"],
                "verbose_name": "Ctto. General Columna 3",
                "verbose_name_plural": "Ctto. General Columna 3",
            },
        ),
    ]
