# Generated by Django 4.1.1 on 2022-10-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Descripcion_Servicios_Aicros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("texto_1", models.TextField()),
            ],
            options={
                "verbose_name": "Descripción Servicio Aicros",
                "verbose_name_plural": "Descripción Servicio Aicros",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Encabezado_Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("texto_1", models.TextField()),
                ("texto_2", models.TextField()),
            ],
            options={
                "verbose_name": "Encabezado Servicio",
                "verbose_name_plural": "Encabezado Servicio",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Servicio_Aicros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ícono", models.ImageField(upload_to="Página Servicios/Ícono")),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Servicio Aicros",
                "verbose_name_plural": "Servicio Aicros",
                "ordering": ["id"],
            },
        ),
    ]
