# Generated by Django 4.1.1 on 2022-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Descripcion_Productos_Aicros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("texto_1", models.TextField()),
            ],
            options={
                "verbose_name": "Descripción Productos Aicros",
                "verbose_name_plural": "Descripción Productos Aicros",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Descripcion_Productos_Distribuidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("texto_1", models.TextField()),
            ],
            options={
                "verbose_name": "Descripción Productos Distribuidos",
                "verbose_name_plural": "Descripción Productos Distribuidos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Encabezado_Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("texto1", models.TextField()),
                ("texto2", models.TextField()),
            ],
            options={
                "verbose_name": "Encabezado Producto",
                "verbose_name_plural": "Encabezado Producto",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Producto_Aicros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Productos/Aicros/Imágenes",
                    ),
                ),
                ("título", models.CharField(blank=True, max_length=200, null=True)),
                ("descripción", models.TextField()),
                (
                    "ícono",
                    models.ImageField(
                        blank=True, null=True, upload_to="Página Productos/Aicros/Ícono"
                    ),
                ),
                ("nombre_Botón", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Producto Aicros",
                "verbose_name_plural": "Producto Aicros",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Producto_Distribuido_Aicros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Productos/Aicros/Distribuidos/Imágenes",
                    ),
                ),
                ("título", models.CharField(blank=True, max_length=200, null=True)),
                ("descripción", models.TextField()),
                (
                    "ícono",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Productos/Aicros/Distribuidos/Ícono",
                    ),
                ),
                ("nombre_Botón", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Producto Distribuido Aicros",
                "verbose_name_plural": "Producto Distribuido Aicros",
                "ordering": ["id"],
            },
        ),
    ]
