# Generated by Django 4.1.1 on 2022-11-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto_distribuido_aicros",
            options={
                "ordering": ["id"],
                "verbose_name": "Producto Distribuido",
                "verbose_name_plural": "Producto Distribuido",
            },
        ),
    ]
