# Generated by Django 4.1.1 on 2022-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anno_Historia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("número", models.CharField(max_length=50)),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Año de Historia",
                "verbose_name_plural": "Año de Historia",
                "ordering": ["número"],
            },
        ),
        migrations.CreateModel(
            name="Encabezado_Nosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("texto_1", models.TextField()),
                ("texto_2", models.TextField()),
            ],
            options={
                "verbose_name": "Encabezado Nosotros",
                "verbose_name_plural": "Encabezado Nosotros",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Evento_Columna_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Evento Columna 1",
                "verbose_name_plural": "Evento Columna 1",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Evento_Columna_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Evento Columna 2",
                "verbose_name_plural": "Evento Columna 2",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Evento_Columna_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Evento Columna 3",
                "verbose_name_plural": "Evento Columna 3",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Miembro_de_Trabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Nosotros/Miembro de Trabajo/Imágenes",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Miembro de Trabajo",
                "verbose_name_plural": "Miembro de Trabajo",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Mision_Nosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Misión",
                "verbose_name_plural": "Misión",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Valores_Nosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Valores",
                "verbose_name_plural": "Valores",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Vision_Nosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Visión",
                "verbose_name_plural": "Visión",
                "ordering": ["id"],
            },
        ),
    ]
