# Generated by Django 4.1.1 on 2023-02-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Nosotros", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Evento_Columna_2",
            new_name="Evento",
        ),
        migrations.DeleteModel(
            name="Evento_Columna_1",
        ),
        migrations.DeleteModel(
            name="Evento_Columna_3",
        ),
        migrations.AlterModelOptions(
            name="evento",
            options={
                "ordering": ["id"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Evento",
            },
        ),
    ]
