# Generated by Django 4.1.1 on 2023-02-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Nosotros", "0002_rename_evento_columna_2_evento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={
                "ordering": ["título"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Evento",
            },
        ),
        migrations.AlterField(
            model_name="evento",
            name="descripción",
            field=models.TextField(max_length=430),
        ),
    ]
